---
title: "functions-lesson"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Test Data
```{r test data}

airtemps <- c(212,30.3, 78, 32)
celcius1 <- (airtemps[[1]]-32)*5/9
celcius2 <- (airtemps[[2]]-32)*5/9
celcius3 <- (airtemps[[3]]-32)*5/9
celcius4 <- (airtemps[[4]]-32)*5/9

```

# Create your first function

```{r}
fahr_to_celcius <- function(fahr) {
  celcius <- (fahr - 32) *5/9
  return (celcius)
}


```

# Use the function 
```{r}

celcius_test<-fahr_to_celcius(airtemps)


```


# Create a function to calculate F from C
```{r}
celcius_to_fahr <- function(celcius) {
  fahr <- (celcius * 9/5)+32
  return(fahr)
}

mysum <- function(x,y) {
  return(x+y)
}

fahr_test <- celcius_to_fahr(celcius_test)

```
 
# Create a multi part function 
```{r}
covert_temps <- function(fahr) {
  celcius <- fahr_to_celcius(fahr)
  kelvin <- celcius + 273.15
  return(list(fahr=fahr,celcius=celcius, kelvin=kelvin))
}

covert_temps(32)

temps_df<-data.frame(covert_temps(seq(-100,100,10)))

```

#creating a new ggplot theme
```{r}

custom_theme <- function(base_size = 10) {
    ggplot2::theme(
      axis.ticks       = ggplot2::element_blank(),
      text             = ggplot2::element_text(family = 'Calibri', color = 'gray30', size = base_size),
      plot.title       = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold'),
      panel.background = ggplot2::element_blank(),
      legend.position  = 'bottom',
      panel.border     = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_line(colour = 'grey90', size = .25),
      legend.key       = ggplot2::element_rect(colour = NA, fill = NA),
      axis.line        = ggplot2::element_blank()
      )
}

library(ggplot2)

ggplot(temps_df, mapping=aes(x=fahr, y=celcius, color=kelvin)) +
    geom_point() +
    custom_theme(10)
```

